#!/usr/bin/env bash
set -uo pipefail

# Source utility functions
. ./scripts/url-utils.sh
. ./scripts/progress.sh
. ./scripts/toml-utils.sh
. ./scripts/log.sh

show_help() {
    cat << EOF
NAME
    gen-readme.sh - Generate README.md files from platform TOML configurations

SYNOPSIS
    gen-readme.sh [OPTIONS] <toml_file>

DESCRIPTION
    This script reads a platform TOML file (generated by gen-platform-toml.sh) and
    creates a human-readable README.md file with decoded filenames and metadata.

ARGUMENTS
    toml_file
        Path to the platform TOML file (e.g., gb.toml)

OPTIONS
    -h, --help
        Display this help message and exit.

OUTPUT
    Creates a README.md file in the same directory as the input TOML file.
    The README contains:
    - Platform title and description
    - Generation date and time (UTC)
    - Source URL
    - Total number of files
    - Total download size (calculated from source)
    - Complete list of human-readable filenames

EXAMPLES
    gen-readme.sh testconfigs/gb.toml
    gen-readme.sh --help

SEE ALSO
    gen-platform-toml.sh - Generate TOML files by scraping Myrient pages
    myrient-dl.sh - Download ROMs using TOML configurations

EOF
}

# Parse options
while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            show_help
            exit 0
            ;;
        -*)
            info "Unknown option: $1"
            info "Use -h or --help for usage"
            exit 1
            ;;
        *)
            break
            ;;
    esac
done

# Check arguments
if [[ $# -ne 1 ]]; then
    info "Usage: gen-readme.sh [OPTIONS] <toml_file>"
    info "Use -h or --help for detailed help"
    exit 1
fi

# Check .toml file
TOML_FILE="$1"
if [[ ! -f "$TOML_FILE" ]]; then
    error "File not found: $TOML_FILE"; exit 1
fi

info "Generating README for $TOML_FILE"

# Parse TOML into JSON
JSON=$(parse_toml "$TOML_FILE")

# Check if this is a meta TOML
if printf "%s" "$JSON" | jq -e 'has("platform_tomls")' > /dev/null 2>&1; then
    # Handle meta TOML
    mapfile -t PLATFORM_FILES < <(printf "%s" "$JSON" | jq -r '.platform_tomls[]')

    # Generate READMEs for all individual platforms
    for platform_file in "${PLATFORM_FILES[@]}"; do
        platform_path="$(dirname "$TOML_FILE")/$platform_file"
        platform_readme_path="$(dirname "$platform_path")/README.md"
        if [[ -f "$platform_path" && ! -f "$platform_readme_path" ]]; then
            "$0" "$platform_path"
        fi
    done
    
    # Now calculate summary info for all platforms
    TOTAL_FILES=0
    TOTAL_SIZE_BYTES=0
    PLATFORM_SUMMARY="| PLATFORM | FILES | SIZE | DIRECTORY |\n| --- | --- | --- | --- |\n"

    for platform_file in "${PLATFORM_FILES[@]}"; do
        platform_path="$(dirname "$TOML_FILE")/$platform_file"
        if [[ -f "$platform_path" ]]; then
            platform_json=$(parse_toml "$platform_path")
            platform_name=$(basename "$platform_file" .toml | tr '[:lower:]' '[:upper:]')
            platform_directory=$(printf "%s" "$platform_json" | jq -r '.directory // empty')
            mapfile -t platform_files < <(printf "%s" "$platform_json" | jq -r '.files[]')

            TOTAL_FILES=$((TOTAL_FILES + ${#platform_files[@]}))

            # Extract size and add
            platform_readme_path="$(dirname "$platform_path")/README.md"
            if [[ -f "$platform_readme_path" ]]; then
                # Extract size line and remove label
                platform_size_line=$(grep '\- \*\*Total Size\*\*:' "$platform_readme_path" | sed 's/.*: //' | head -1)
                if [[ -n "$platform_size_line" && "$platform_size_line" != "Unknown" ]]; then
                    # Extract the IEC size, remove B and " "
                    platform_size_iec=$(echo "$platform_size_line" | sed 's/(.*)//; s/B//; s/ //')
                    if [[ -n "$platform_size_iec" ]]; then
                        platform_size_bytes=$(numfmt --from=iec-i "$platform_size_iec")
                        TOTAL_SIZE_BYTES=$((TOTAL_SIZE_BYTES + platform_size_bytes))
                    fi
                fi
            fi
            relative_platform_readme_path="$(dirname "$platform_file")/README.md"
            PLATFORM_SUMMARY="${PLATFORM_SUMMARY}| [${platform_name}](${relative_platform_readme_path}) | ${#platform_files[@]} Files | ${platform_size_line} | ${platform_directory} |\n"
        fi
    done

    if [[ $TOTAL_SIZE_BYTES -eq 0 ]]; then
        TOTAL_SIZE_FORMATTED="Unknown"
    else
        # Generate initial string as IEC (SI), then add spaces
        TOTAL_SIZE_FORMATTED="$(numfmt --to=iec-i "$TOTAL_SIZE_BYTES")B ($(numfmt --to=si "$TOTAL_SIZE_BYTES")B)"
        TOTAL_SIZE_FORMATTED=$(echo "$TOTAL_SIZE_FORMATTED" | sed 's/\([0-9]\)\([A-Z]\)/\1 \2/g')

        # Generate meta README
        README_FILE="$(dirname "$TOML_FILE")/README.md"
    
        {
            echo "# Multi-Platform ROM Collection"
            echo ""
            echo "This collection contains ROMs for multiple gaming platforms."
            echo ""
            echo "## Metadata"
            echo ""
            echo "- **Generated**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            echo "- **Total Platforms**: ${#PLATFORM_FILES[@]}"
            echo "- **Total Files**: $TOTAL_FILES"
            echo "- **Total Size**: $TOTAL_SIZE_FORMATTED"
            echo ""
            echo "## Included Platforms"
            echo ""
            printf "%b" "$PLATFORM_SUMMARY"
            echo ""
            echo "## Download"
            echo ""
            echo "To download all platforms in this collection:"
            echo ""
            echo "\`\`\`bash"
            echo "./myrient-dl.sh \"$TOML_FILE\""
            echo "\`\`\`"
            echo ""
            echo "Or download to a custom directory:"
            echo ""
            echo "\`\`\`bash"
            echo "./myrient-dl.sh -o /path/to/directory \"$TOML_FILE\""
            echo "\`\`\`"
        } > "$README_FILE" & show_spinner -i $! -p "Writing README: "; info "Generated summary README.md for $TOML_FILE"; exit 0
    fi
else
    # Get & check site
    SITE=$(printf "%s" "$JSON" | jq -r '.site // empty')
    if [[ -z "$SITE" ]]; then error "Site not found in: $TOML_FILE"; exit 1; fi

    # Get & check Path Directory
    PATH_DIRECTORY=$(printf "%s" "$JSON" | jq -r '.path_directory // empty')
    if [[ -z "$PATH_DIRECTORY" ]]; then error "Path Directory not found in: $TOML_FILE"; exit 1; fi

    # Get & check Download Directory
    DIRECTORY=$(printf "%s" "$JSON" | jq -r '.directory // empty')
    if [[ -z "$DIRECTORY" ]]; then error "Directory not found in: $TOML_FILE"; exit 1; fi

    mapfile -t FILES < <(printf "%s" "$JSON" | jq -r '.files[]')

    # Construct source URL
    SOURCE_URL_DEC="${SITE}${PATH_DIRECTORY}"
    SOURCE_URL_ENC="${SITE}$(url_encode "${PATH_DIRECTORY}")"

    # Generate platform name from directory
    PLATFORM_NAME=$(basename "$DIRECTORY" / | tr '[:lower:]' '[:upper:]')

    # Scrape file sizes from the source page
    HTML=$(curl -s "$SOURCE_URL_ENC"); info "Scraping file sizes from: $SOURCE_URL_DEC"

    # Calculate total size
    TOTAL_SIZE_BYTES=0; FILE_INDEX=0; FILES_TOTAL=${#FILES[@]}
    FILE_SUMMARY="| GAME | TAGS | SIZE |\n| --- | --- | --- |\n"

    for file in "${FILES[@]}"; do
        # Progress Bar
        if [[ -t 1 ]]; then
            show_progress -c $FILE_INDEX -t $FILES_TOTAL -m "Parsing files"
        else
            info "Parsing $file"
        fi

        # Extract file size from Myrient & strip the " " and "B"
        file_size=$(echo "$HTML" | grep -F -A2 "$file" | grep '<td class="size">' | sed 's/.*<td class="size">//;s/B<\/td>.*//;s/ //' | head -1)
        game_name=$(echo "$file" | sed 's/ (.*//' | head -1)
        game_tags=$(echo "$file" | sed 's/\.[^.]*$//; s/[^()]*//')

        FILE_SUMMARY="${FILE_SUMMARY}| ${game_name} | ${game_tags} | ${file_size}B |\n"

        if [[ -n "$file_size" && "$file_size" != "-" ]]; then
            file_bytes=$(numfmt --from=iec-i "$file_size")
            TOTAL_SIZE_BYTES=$((TOTAL_SIZE_BYTES + file_bytes))
        fi
        ((++FILE_INDEX))
    done

    # Format total size using numfmt for automatic IEC/SI formatting
    if [[ $TOTAL_SIZE_BYTES -eq 0 ]]; then
        TOTAL_SIZE_FORMATTED="Unknown"
    else
        # Generate initial string as IEC Size (SI Size), then add spaces
        TOTAL_SIZE_FORMATTED="$(numfmt --to=iec-i "$TOTAL_SIZE_BYTES")B ($(numfmt --to=si "$TOTAL_SIZE_BYTES")B)"
        TOTAL_SIZE_FORMATTED=$(echo "$TOTAL_SIZE_FORMATTED" | sed 's/\([0-9]\)\([A-Z]\)/\1 \2/g')
    fi

    # Generate README
    README_FILE="$(dirname "$TOML_FILE")/README.md"

    {
        echo "# $PLATFORM_NAME ROM Collection"
        echo ""
        echo "This collection contains ROMs for the $PLATFORM_NAME."
        echo ""
        echo "## Metadata"
        echo ""
        echo "- **Generated**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        echo "- **Source URL**: [$SOURCE_URL_DEC]($SOURCE_URL_ENC)"
        echo "- **Total Files**: ${#FILES[@]}"
        echo "- **Total Size**: $TOTAL_SIZE_FORMATTED"
        echo "- **Platform Directory**: $DIRECTORY"

        echo ""
        echo "## ROM Files"
        echo "<details>"
        echo "<summary>The following ${#FILES[@]} ROM files are included in this collection:</summary>"
        echo ""
        printf "%b" "$FILE_SUMMARY"
        echo ""
        echo "</details>"
        echo ""
        echo "## Download"
        echo ""
        echo "To download all ROMs in this collection:"
        echo ""
        echo "\`\`\`bash"
        echo "./myrient-dl.sh \"$TOML_FILE\""
        echo "\`\`\`"
        echo ""
        echo "Or download to a custom directory:"
        echo ""
        echo "\`\`\`bash"
        echo "./myrient-dl.sh -o /path/to/directory \"$TOML_FILE\""
        echo "\`\`\`"
    } > "$README_FILE" & show_spinner -i $! -p "Writing README: "; info "Generated $README_FILE"
fi
