[package]
name = "roms-ac"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.13", features = ["json", "gzip", "rustls", "blocking"] }
log = "0.4"
env_logger = "0.10"
scraper = "0.25"
toml = "0.9"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
md5 = "0.8"
anyhow = "1.0"
percent-encoding = "2.3"
regex = "1.12"
chrono = { version = "0.4", features = ["clock"] }
byte-unit = "5.2.0"
indicatif = "0.18"
indicatif-log-bridge = "0.2"
html-escape = "0.2"
urlencoding = "2.1"
futures = "0.3"
dirs = "6.0"
ratatui = "0.29"
crossterm = "0.28"
tui-textarea = "0.7"

[dev-dependencies]
tempfile = "3.0"
